import Header from "@/components/Header";
import { CartProvider } from "@/context/CartContext";
import { auth0 } from "@/lib/autho0";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth0.getSession();
  console.log("main--->", session);
  const isLoggedIn = !!session?.user;
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >

        <CartProvider>
          <Header isLoggedIn={isLoggedIn} />
          {children}
        </CartProvider>
        ;
      </body>
    </html>
  );
}
